packages = [
  "bat",
  "bazelisk",
  "bloaty",
  "btop",
  "cmake",
  "curl",
  "eza",
  "fd",
  "fzf",
  "graphviz",
  "jujutsu",
  "lazygit",
  "mermaid-cli",
  "ninja",
  "node",
  "pnpm",
  "python",
  "ripgrep",
  "rustup",
  "starpls",
  "unzip",
  "uv",
  "wget",
  "yazi",
]
