# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- ghostty +new-window
bindd = SUPER, SPACE, App launcher, exec, uwsm-app -- onagre
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, cmd-launch-browser
bindd = SUPER SHIFT, B, Browser, exec, cmd-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, cmd-launch-browser --private
bindd = SUPER SHIFT, N, Editor, exec, zeditor
